// app/components/icons/featureIcons.js
import { percent } from "framer-motion";
import {
  Shield,
  Droplets,
  Flame,
  Sparkles,
  Leaf,
  Hammer,
  Layers,
  Sun,
  Wind,
  Construction,
  House,
  WavesArrowDownIcon,
  ShieldCheckIcon,
  Sprout,
  Martini,
  ShieldOffIcon,
  Heater,
  Scale,
  IndianRupee,
  Percent,
  ShieldOff,
  // Sparkles,
} from "lucide-react";

export const featureIconMap = {
  scratch: Shield,
  water: Droplets,
  heat: Flame,
  durable: Hammer,
  eco: Leaf,
  // design: Sparkles,
  layers: Layers,
  uv: Sun,
  ventilation: Wind,
  maintenance:Construction,
  ease:House,
  resistance:WavesArrowDownIcon,
  check:ShieldCheckIcon,
  eco:Sprout,
  glass:Martini,
  stars:Sparkles,
  shield:ShieldOff,
  heat:Heater,
  lightweight: Scale,
  cost:IndianRupee,
  percent:Percent,
  anti:ShieldOffIcon,
};